name: Schedule Workflow Run on Every 10 Min

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * 0'
    - cron: '0 0 * * 5,6'

jobs:
  Schedule-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello, I am cron scheduler"

      - name: Time
        run: |
          current_datetime=$(date)
          echo "Current Date & Time: $current_datetime"
